[FEAT] week7 example 파일에 미션 코드 추가
UMC-ERICA/7th-spring-a pull request #12
Opened 2024-11-14 10:08 UTC by jmsb02

## Summary

- 7주차 미션 내용입니다.

## Describe your code

-  자세한 내용은 [링크](https://www.notion.so/makeus-challenge/Chapter-7-API-a0c8b6753ddb44189d8ca0a3d12ed1ea) 참조하시면 되겠습니다.

## Checklist

- [ ] 휘건
- [ ] 마커스
- [ ] 임미

2024-11-15 01:57 UTC, msk226 requested changes
급하게 하다보니 이렇게 되었네요 ㅜ 수정하였습니다!

2024-11-15 01:59 UTC, msk226 commented on 잼/spring/src/main/java/umc/spring/example/apiPayload/code/status/ErrorStatus.java
> +public enum ErrorStatus implements BaseErrorCode {
만약 처리해야 할 에러 메시지들이 많아지더라도 해당 클래스에서 쭉 관리 하는게 좋을까요? 아님 분리? 어떻게 생각하시나요~

2024-11-15 02:05 UTC, msk226 reviewed
커밋 단위를 조금 더 작게 가져가면 더 좋을 것 같다고 생각합니다! 임미님 PR 참고 하시면 좋을 것 같습니다~

2024-11-15 03:47 UTC, jmsb02 commented
> 커밋 단위를 조금 더 작게 가져가면 더 좋을 것 같다고 생각합니다! 임미님 PR 참고 하시면 좋을 것 같습니다~

넵 참고하고 수정하도록 하겠습니다 감사합니다!

2024-11-15 03:49 UTC, jmsb02 commented on 잼/spring/src/main/java/umc/spring/example/apiPayload/code/status/ErrorStatus.java
> +public enum ErrorStatus implements BaseErrorCode {
프로젝트 규모가 커지면 도메인/기능별로 분리하는 게 좋을 것 같습니다! (ex.UserErrorStatus,OrderErrorStatus ...) 그래야 유지보수성과 학장성이 향상할 것같아서요

2024-11-15 04:35 UTC, msk226 approved these changes
이번주도 고생 하셨습니다~

2024-11-15 04:44 UTC, gdbs1107 commented on 잼/spring/src/main/java/umc/spring/example/apiPayload/code/status/ErrorStatus.java
> +public enum ErrorStatus implements BaseErrorCode {
이 부분에 대해서 저도 고민이 되는 것 같습니다

에러메세지들이 많아지면서 클래스를 분리하게 된다면 에러 핸들링에 대해서 완전히 이해해야 가능할 것 같아, 공부를 더 열심히 해야할 것 같습니다. 고생하셨습니다!

2024-11-16 07:35 UTC, Hwigun46 approved these changes
한주동안 고생 많으셨습니다 !!

2024-11-16 07:35 UTC, merged