5주차_미션_엔티티 구현
UMC-ERICA/7th-spring-a pull request #5
Opened 2024-10-31 05:24 UTC by Hwigun46

## Summary

- 5주차 미션: 본인 ERD를 토대로 엔티티 구현( 매핑, column 세부 설정 포함)

## Describe your code

- 최대한 통일성 있게 엔티티를 구현했습니다

## Checklist

- [ ] 마커스
- [ ] 임미
- [ ] 잼

2024-10-31 10:35 UTC, gdbs1107 approved these changes

2024-10-31 10:35 UTC, gdbs1107 commented on 휘건/spring/src/main/java/UMC/spring/domain/Agreement.java
> +    @Lob
@Lob 이거는 뭔가요?!

2024-11-01 00:18 UTC, msk226 requested changes

2024-11-01 00:18 UTC, msk226 commented on 휘건/spring/src/main/resources/application.yml
> +          auto: create
Github에 올릴 때는 항상 `update`로 올려주셔야 합니다! 

이 상태로 배포된 서버에 올라가게 되면, 테이블이 새로 정의 되면서 기존에 있던 데이터들이 싹 다 사라질거에요...

2024-11-01 00:18 UTC, msk226 commented on 휘건/spring/src/main/resources/application.yml
> +    username: ${LOCAL_DB_USERNAME}
민감한 정보는 이렇게 가려서 올려주셨네요!

2024-11-01 00:26 UTC, msk226 commented on 휘건/spring/src/main/java/UMC/spring/domain/Alarm.java
> +    @ManyToOne(fetch = FetchType.LAZY)
해당 애노테이션의 의미 및 역할이 무엇인지 설명 듣고 싶습니다! LAZY 말고 다른 옵션도 있나요?

2024-11-01 00:26 UTC, msk226 commented on 휘건/spring/src/main/java/UMC/spring/domain/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
해당 애노테이션을 쓰면 ID가 어떤 방식으로 생성 되는 건가요?

2024-11-01 00:26 UTC, msk226 commented on 휘건/spring/src/main/java/UMC/spring/domain/Review.java
> +    private BigDecimal rate;
BigDecimal은 사용한 경험이 거의 없는 것 같은데, 다른 타입과의 차이점이 궁금합니다!

2024-11-01 04:06 UTC, Hwigun46 commented on 휘건/spring/src/main/resources/application.yml
> +          auto: create
앗 ,,, 테스트 진행하다가 놓쳤던 사항이네요 .. 다음부터는 꼭 꼭 인지하면서 commit을 하겠습니다 !

2024-11-01 04:38 UTC, Hwigun46 commented on 휘건/spring/src/main/java/UMC/spring/domain/Alarm.java
> +    @ManyToOne(fetch = FetchType.LAZY)
@ ManyToOne 어노테이션은 JPA에서 다대일 관게를 맵핑할 때 사용됩니다!

단어 뜻 그대로 다에서 일로 향하는 방향을 뜻합니다.
여기서는 알람 여러개가 회원 한명으로 향하는 상황입니다. 

fetch는 JPA에서 연관된 엔티티를 어느 시점에 로딩할지를 결정하는 설정입니다.
관계가 맺어져 있을 때 바로 엔티티를 가져올지 혹은 필요할 때까지 기다렸다가 가져올지, 이런식으로 여러 가지 시점을 설정합니다.

FetchType은 EAGER 와 LAZY 두가지가 있습니다.

EAGER: 관계 엔티티를 즉시 같이 조회하는 타입입니다. 복잡한 관계에서는 성능에 영향을 줄 가능성이 있습니다.

LAZY: 필요한 시점까지 기다리다 필요 시점에 데이터를 로딩하는 타입입니다. 성능 최적화를 위해 많이 사용이 됩니다.

LAZY 타입은 N+1 문제의 원인이 될수도 있어 추가적인 배치 사이즈 설정, @ EntityGraph 사용, Join Fetch 사용 등으로 해결할 수 있습니다

2024-11-01 04:39 UTC, Hwigun46 commented on 휘건/spring/src/main/java/UMC/spring/domain/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
@ Id 를 통해 JPA가 해당 필드를 PK로 인식하게 됩니다.

@ GeneratedValue는 말 그대로 값을 만들어내는 부분입니다. 전략에 따라 자동 생성 되는 값들이 달라집니다.

IDENTITY 타입의 전략을 채용하게 되면 MySQL에 있는 auto_increment 처럼 값이 자동으로 증가되면서 즉시 생성됩니다 !

이외에도 여러 타입이 있는데 사용할려는 용도에 따라 달라집니다 ( MySQL, Oracle 등)

SEQUENCE 전략은 데이터베이스 시퀀스를 사용해 ID를 생성합니다. ( 미리 정의된 순서대로 고유한 숫자를 반환)
TABLE 전략은 별도 테이블에서 ID를 관리합니다.( 시퀀스 값이 아닌 전화번호와 같은 특정 값이 PK로 사용될 때)
AUTO는 JPA가 자동으로 생성 전략을 선택합니다.

2024-11-01 04:39 UTC, Hwigun46 commented on 휘건/spring/src/main/java/UMC/spring/domain/Review.java
> +    private BigDecimal rate;
저도 이번 스터디를 진행하면서 알게 된 타입입니다 !

정확한 소수 계산을 위한 클래스입니다.
해당 클래스를 사용해서 소수 표현을 하게 되면 기본 연사자(+,-,*,/) 를 사용할 수 없습니다. 
대신에 add()나 divide()와 같은 메서드를 통해 계산을 하게 되는데 보다 정확한 값을 얻을 수 있습니다.

float 나 double 같은 경우는 이진수 표현의 한계로 인해 정확한 표현이 어렵고 근사값으로 저장되는 경우가 종종 있습니다.
하지만 BigDecimal은 정수와 소수부를 분리하여 계산하여 정확한 계산이 가능합니다!

2024-11-01 05:35 UTC, msk226 approved these changes
5주차 학습 하시느라 수고 많으셨습니다!

2024-11-01 06:24 UTC, merged